# window border
window.active.border.color: #d9c76f
window.inactive.border.color: #d0c7a2

# ToggleKeybinds status indicator
window.active.indicator.toggled-keybind.color: #ffb4ab

# window titlebar background
window.active.title.bg.color: #d9c76f
window.inactive.title.bg.color: #d0c7a2

window.active.label.text.color: #383000
window.inactive.label.text.color: #363016
window.label.text.justify: center

# window button hover overlay
window.button.hover.bg.color: #2c2a21

# window buttons
window.active.button.unpressed.image.color: #383000
window.inactive.button.unpressed.image.color: #383000

# menu
menu.border.color: #383000
menu.items.bg.color: #d9c76f
menu.items.text.color: #383000
menu.items.active.bg.color: #d0c7a2
menu.items.active.text.color: #363016
menu.separator.color: #383000
menu.title.bg.color: #d9c76f
menu.title.text.color: #383000

# on screen display (window-cycle dialog)
osd.bg.color: #d9c76f
osd.border.color: #383000
osd.label.text.color: #383000
osd.window-switcher.preview.border.color: #969180
