[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml",
]

[window]
opacity = 0.98
decorations = "full"
decorations_theme_variant = "Dark"

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]
