[colors.primary]
background = '#15130c'
foreground = '#e8e2d4'

[colors.cursor]
text = '#15130c'
cursor = '#e8e2d4'

[colors.vi_mode_cursor]
text = '#15130c'
cursor = '#d9c76f'

[colors.search.matches]
foreground = '#4a4739'
background = '#a8d0b5'

[colors.search.focused_match]
foreground = '#4a4739'
background = '#d9c76f'

[colors.footer_bar]
foreground = '#4a4739'
background = '#e8e2d4'

[colors.hints.start]
foreground = '#4a4739'
background = '#d0c7a2'

[colors.hints.end]
foreground = '#4a4739'
background = '#d0c7a2'

[colors.selection]
text = '#ccc6b5'
background = '#4a4739'


[colors.normal]
black   = '#4a4739'
red     = '#ffb4ab'
green   = '#d9c76f'
yellow  = '#d0c7a2'
blue    = '#a8d0b5'
magenta = '#d9c76f'
cyan    = '#d0c7a2'
white   = '#e8e2d4'


[colors.bright]
black   = '#969180'
red     = '#ffb4ab'
green   = '#d9c76f'
yellow  = '#d0c7a2'
blue    = '#a8d0b5'
magenta = '#d9c76f'
cyan    = '#d0c7a2'
white   = '#e8e2d4'


[colors.dim]
black   = '#4a4739'
red     = '#ffb4ab'
green   = '#d9c76f'
yellow  = '#d0c7a2'
blue    = '#a8d0b5'
magenta = '#d9c76f'
cyan    = '#d0c7a2'
white   = '#e8e2d4'
